# .github/workflows/databox-test.yml
name: test Databox token
on: { workflow_dispatch: {} }

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push test metric to THIS token
        run: |
          set -euo pipefail
          JSON='{"data":[{"$enchant_debug":123}]}'
          curl -sv -u "${{ secrets.DATABOX_TOKEN }}:" \
            -H "Content-Type: application/json" \
            -d "$JSON" \
            https://push.databox.com/data \
            -D /tmp/headers -o /tmp/body
          echo "----- HTTP HEADERS -----"; cat /tmp/headers
          echo "----- RESPONSE BODY -----"; cat /tmp/body
