name: test Databox token
on: { workflow_dispatch: {} }

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push test metric to Databox (v2)
        run: |
          set -euo pipefail
          JSON='{"data":[{"$enchant_debug":123}]}'
          curl -sS -u "${{ secrets.DATABOX_TOKEN }}:" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.databox.v2+json" \
            -d "$JSON" \
            https://push.databox.com/data \
            -D /tmp/h -o /tmp/b
          echo "----- HTTP -----"; head -n 1 /tmp/h
          echo "----- Body -----"; cat /tmp/b
