name: probe Databox push endpoint
on: { workflow_dispatch: {} }

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Try common Databox endpoints until one works
        env:
          TOKEN: ${{ secrets.DATABOX_TOKEN }}
        run: |
          set -euo pipefail
          endpoints=(
            "https://push.databox.com/data"
            "https://push.databox.com/api/v1/data"
            "https://push.databox.com/v1/data"
            "https://push.databox.com/"   # last resort (often HTML)
          )
          payload='{"data":[{"$enchant_debug":123}]}'

          pass=0
          for url in "${endpoints[@]}"; do
            echo ">>> Trying $url"
            hdr=$(mktemp); body=$(mktemp)
            # Basic auth: username is the token, blank password
            curl -sS -u "$TOKEN:" \
              -H "Content-Type: application/json" \
              -H "Accept: application/json" \
              -d "$payload" \
              -D "$hdr" "$url" -o "$body" || true

            code=$(awk 'NR==1{print $2}' "$hdr")
            ctype=$(awk -F': ' 'tolower($1)=="content-type"{print $2; exit}' "$hdr")
            echo "HTTP $code | content-type: ${ctype:-<none>}"
            echo -n "Body (first 200 chars): "; head -c 200 "$body" || true; echo; echo

            if grep -q '"status":"ok"' "$body"; then
              echo "✅ SUCCESS using $url"
              echo "URL=$url" >> "$GITHUB_ENV"
              pass=1
              break
            fi
          done

          if [ "$pass" -ne 1 ]; then
            echo "❌ None of the endpoints returned JSON ok. Check token or share the output above."
            exit 1
          fi

      - name: Summary
        run: |
          echo "Work
