name: test Databox token
on: { workflow_dispatch: {} }

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push test metric to THIS token
        run: |
          set -euo pipefail
          echo "Using token (first 8 chars): ${DATABOX_TOKEN:0:8}******"
          JSON='{"data":[{"$enchant_debug":123,"date":"2025-01-01 00:00:00"}]}'
          curl -sv -u "${DATABOX_TOKEN}:" \
            -H "Content-Type: application/json" \
            -d "$JSON" \
            https://push.databox.com \
            -D /tmp/headers -o /tmp/body
          echo "----- HTTP HEADERS -----"; cat /tmp/headers
          echo "----- RESPONSE BODY -----"; cat /tmp/body
        env:
          DATABOX_TOKEN: ${{ secrets.DATABOX_TOKEN }}
